import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";

export default function Home() {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.tittle}>Bisa Technical Challenge</h1>
        <h3>by Tomás Peñaloza</h3>
        <button onClick={() => router.push("/technical/challenge")}>
          Go to '/technical/challenge'
        </button>
        <button onClick={() => router.push("/api")}>Go to '/api'</button>
      </main>
    </div>
  );
}
